#!/bin/bash

# Script to help install Swift 6.0 toolchain without Xcode
# This allows building the macOS app using just command-line tools

echo "Swift 6.0 Toolchain Installation Guide"
echo "======================================="
echo ""
echo "To build the macOS app without Xcode, you need Swift 6.0."
echo "Your current Swift version: $(swift --version | head -1)"
echo ""
echo "Steps to install Swift 6.0 toolchain:"
echo ""
echo "1. Download Swift 6.0 for macOS from:"
echo "   https://www.swift.org/download/"
echo ""
echo "2. Look for the latest 'Release' toolchain for macOS"
echo "   (e.g., swift-6.0-RELEASE-macos.pkg or newer)"
echo ""
echo "3. Install the .pkg file by double-clicking it"
echo ""
echo "4. Activate the toolchain with one of these methods:"
echo ""
echo "   METHOD A - Temporary (current terminal session only):"
echo "   export TOOLCHAINS=swift"
echo ""
echo "   METHOD B - Set as default:"
echo "   export TOOLCHAINS=\$(plutil -extract CFBundleIdentifier raw /Library/Developer/Toolchains/swift-latest.xctoolchain/Info.plist)"
echo "   # Add this to your ~/.zshrc or ~/.bashrc to make it permanent"
echo ""
echo "5. Verify installation:"
echo "   swift --version"
echo "   # Should show Swift 6.0 or later"
echo ""
echo "6. Build the app:"
echo "   cd $(pwd)"
echo "   swift build -c release"
echo "   .build/release/MacState"
echo ""
echo "Alternative: Install Xcode from the App Store (includes Swift 6.0)"
echo ""
